name: CI

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: verify repository
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v1.4.4
        with:
            node-version: 14

      - name: install dependencies
        run: npm install

      - name: run eslint
        run: npm run lint
